### ISSUE TITLE
Players Can Walk Through Protected Blocks

### ISSUE THREAD

**Issue by ghost** [minetest-mods/areas#20]
I am using the mod in my server but It is a bit buggy isn't it? Players can easily wall through the blocks via breaking blocks and just moving towards.

**Comment by ShadowNinja** [comment]
Yeah, there's nothing I can do about this since movement is entirely client-side.  It's quite trivial to modify the client to be able to noclip and fly without privileges, and the only way to really solve this is with some form of server-side anti-cheat.

Here's a related Minetest engine issue: minetest/minetest#3822

**Comment by beyondlimits** [comment]
"wontfix"?

**Comment by beyondlimits** [comment]
It's supposed to be an engine thing.

minetest/minetest#3822
minetest/minetest#3894
minetest/minetest#6219
