### ISSUE TITLE
Add a hook to change the criteria for what to count for the player area limit

### ISSUE THREAD

**Issue by mk-pmb** [minetest-mods/areas#53]
Currently there's a very simple hard-coded criterion in

```text
chatcommands.lua:402:                   if area.owner == name then
internal.lua:241:               if area.owner == name then
```

As far as I can tell, those places count the number of owned areas, to check whether players exceed the maximum number of allowed areas.

I'm trying to maintain a mod that changes those lines to add additional criteria. It's duplicate code there, and here. Could we factor out those criteria into a function `areas:isLiableLandlordOf(landlordCandidateName, area)`?
That way, the function could easily be changed from the outside.

**Comment by S-S-X** [comment]
Callback API would also allow for example limiting by total protected area volume instead of number of protected areas... or whatever custom rules 👍 

Could even make decision based on tri-state return value from function which would allow just about anything you could imagine while still allowing default core behavior:
https://github.com/minetest-mods/areas/blob/4018c0d20450a106b3bda6627894b130595a7cd6/internal.lua#L214-L222

There just before self.config.self_protection add check through user defined callback and make decision by return value:
- `nil` do nothing, do not return / do not stop. Continue checks without deciding anything.
- `true` immediately return `true`, player can add area no matter what... maybe he has special item that allows protecting otherwise restricted area or something...
    - maybe still go through `canInteractInArea` but option is also to require user to do that
- `false` immediately return `false`, player cannot add area... maybe he still needs to complete few more tasks there and clear hostile entities from area or whatever you can imagine...

**Comment by SmallJoker** [comment]
#74
